function(subdirlist result curdir)
    file(GLOB children RELATIVE ${curdir} ${curdir}/*)
    set(dirlist "")
    foreach(child ${children})
        if ((IS_DIRECTORY ${curdir}/${child}) AND (EXISTS ${curdir}/${child}/CMakeLists.txt))
            list(APPEND dirlist ${child})
            message(${curdir}/${child})
        endif()       
    endforeach()
    set(${result} ${dirlist} PARENT_SCOPE)
endfunction()
